name: LinuxServer-Sonarr
services:
  app:
    image: linuxserver/sonarr:3.0.10
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sonarr/config
        target: /config
      - type: bind
        source: /DATA/AppData/sonarr/tv
        target: /tv
      - type: bind
        source: /DATA/AppData/sonarr/downloads
        target: /downloads
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/r/linuxserver/sonarr/'
  tagline:
    en_us: (formerly NZBdrone) is a PVR for usenet and bittorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.
  developer: LinuxServer.io
  author: WisdomSky
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-banner.png
  title:
    en_us: Sonarr
  category: LinuxServer.io
  project_url: https://sonarr.tv/
  port_map: '8989'
